# This is a basic workflow to help you get started with Actions

name: BUILD SIT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "cicd/apk-builder" ]

# env:
#   RUNNER_OS: ${{ runner.os }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    # runs-on: macOS-latest
    runs-on: self-hosted
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Step 2 - Ubuntu
        run: |
          echo "This step runs only on Ubuntu"
          echo "RUNNER_OS=ubuntu" >> $GITHUB_ENV
        if: runner.os == 'Linux'

      - name: Step 2 - macOS
        run: |
          echo "This step runs only on macOS"
          echo "RUNNER_OS=macos" >> $GITHUB_ENV
        if: runner.os == 'macOS'

      - name: Step 2 - Windows
        run: |
          echo "This step runs only on Windows"
          echo "RUNNER_OS=windows" >> $GITHUB_ENV
        if: runner.os == 'Windows'

      # - name: Check if file exists
      #   run: |
      #     if test -f "scripts/prep.sh"; then
      #       echo "File exists"
      #     else
      #       echo "File does not exist"
      #     fi

      # region Ubuntu Runner ==========================================================
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        if: runner.os == 'Linux'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '27.0.3'
        if: runner.os == 'Linux'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
        if: runner.os == 'Linux'

#      - name: Set up Gradle
#        uses: gradle/gradle-build-action@v2
#        with:
#          gradle-version: 6.1.1
#        if: runner.os == 'Linux'

#      - name: Set Gradle environment variables
#        run: echo "export PATH=${{ steps.gradle-setup.outputs.gradle_bin_dir }}:$PATH" >> $GITHUB_ENV
#        if: runner.os == 'Linux'

      - name: Install Ionic and Cordova
        run: npm install -g @ionic/cli@6.20.9 cordova@11.1.0
        if: runner.os == 'Linux'

      - name: Run custom build script
        run: |
          chmod +x ./scripts/prep.sh
          ./scripts/prep.sh
        if: runner.os == 'Linux'

      - name: Run custom signer script
        env:
          KEYPASS: ${{ secrets.KEYPASS }}
        run: |
          chmod +x ./scripts/sign.sh
          ./scripts/sign.sh $KEYPASS
        if: runner.os == 'Linux'
      # endregion =====================================================================

      # region Windows Runner =========================================================
      - name: Run custom build script
        run: |
          ./scripts/prep.ps1
        if: runner.os == 'Windows'

      - name: Run custom signer script
        run: |
          ./scripts/sign.ps1 ${{ secrets.KEYPASS }}
        if: runner.os == 'Windows'
      # endregion =====================================================================

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # ${{ env.apk_name }}-${{ github.sha }}-${{ github.run_number }}
          tag_name: ${{ env.apk_name }}-${{ github.run_number }}
          release_name: ${{ env.apk_name }}-${{ github.run_number }}
          body: |
            Release: ${{ env.apk_name }}
            SHA: ${{ github.sha }}
            Action Run Number: ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Build Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.zip
          asset_name: app-release.zip
          asset_content_type: application/zip

# ==========================================================================

#      - name: Upload debug APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-dev
#          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

#      - name: Upload release APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-dev
#          path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk

#       - name: Run upload script
#         env:
#           SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
#           SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
#           SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
#         run: |
#           chmod +x ./scripts/upload.sh
#           ./scripts/upload.sh $SHAREPOINT_URL $SHAREPOINT_USERNAME $SHAREPOINT_PASSWORD
