# This is a basic workflow to help you get started with Actions

name: BUILD SIT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "cicd/apk-builder" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 14.x

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Install Ionic and Cordova
        run: npm install -g @ionic/cli@6.20.9 cordova@11.1.0

      - name: Run custom build script
        run: |
          chmod +x ./scripts/prep.sh
          ./scripts/prep.sh

      - name: Run custom signer script
        env:
          KEYPASS: ${{ secrets.KEYPASS }}
        run: |
          chmod +x ./scripts/sign.sh
          ./scripts/sign.sh $KEYPASS

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.apk_name }}-${{ github.sha }}-${{ github.run_number }}
          release_name: ${{ env.apk_name }}-${{ github.sha }}-${{ github.run_number }}
          body: |
            Release: ${{ env.apk_name }}
            SHA: ${{ github.sha }}
            Action Run Number: ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Build Artifact to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app-release.zip
          asset_name: app-release.zip
          asset_content_type: application/zip

      # - name: Run upload script
      #   env:
      #     SHAREPOINT_URL: ${{ secrets.SHAREPOINT_URL }}
      #     SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
      #     SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}
      #   run: |
      #     chmod +x ./scripts/upload.sh
      #     ./scripts/upload.sh $SHAREPOINT_URL $SHAREPOINT_USERNAME $SHAREPOINT_PASSWORD
