# This is a basic workflow to help you get started with Actions

name: BUILD SIT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "cicd/apk-builder" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Get current directory
        id: get_current_dir
        run: echo "::set-output name=current_dir::$(pwd)"
  
      - name: Use current directory
        run: |
          echo "Current directory is: ${{ steps.get_current_dir.outputs.current_dir }}"
          # Use the current directory variable in other commands
          cd ${{ steps.get_current_dir.outputs.current_dir }}
          # Perform other actions in the current directory

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 14.x

      # - name: Set up Android SDK
      #   uses: android-actions/setup-android@v2
      #   with:
      #     sdk-version: '27.0.3'

      - name: Set up Android SDK
        uses: android-actions/setup-android-sdk@v2
        with:
          sdk-platform: 'platforms;android-27'
          ndk-version: '21.4.7075529'

      - name: Set up Android SDK ZipAlign
        run: |
          export ANDROID_HOME=$RUNNER_TEMP/android-sdk
          export PATH=$ANDROID_HOME/build-tools/27.0.3:$PATH

      - name: Set executable permission
        run: chmod +x $ANDROID_HOME/build-tools/27.0.3/zipalign

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 6.1.1

      - name: Set Gradle environment variables
        run: echo "export PATH=${{ steps.gradle-setup.outputs.gradle_bin_dir }}:$PATH" >> $GITHUB_ENV

      - name: Install Ionic and Cordova
        run: npm install -g @ionic/cli@6.20.9 cordova@11.1.0

      - name: Check if build script file exists
        run: |
          if test -f _prep.sh; then
            echo "File exists"
            chmod +x _prep.sh
            echo "Added execute permission to file."
          else
            echo "File does not exist"
          fi

      - name: Run custom build script
        run: |
          echo "Running custom script: Build project..."
          ./_prep.sh

      - name: Check if signer script file exists
        run: |
          if test -f ./sign/sign.sh; then
            echo "File exists"
            chmod +x ./sign/sign.sh
            echo "Added execute permission to file."
          else
            echo "File does not exist"
          fi

      - name: Run custom signer script
        env:
          KEYPASS: ${{ secrets.KEYPASS }}
        run: |
          echo "Running custom script: Sign release APK..."
          ./sign/sign.sh $KEYPASS

      - name: Upload debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-dev
          path: platforms/android/app/build/outputs/apk
